-- INSERT INTO `appointment` (`id`, `doctorId`, `patientId`, `date`, `description`)
-- VALUES (1, 1, 2, '2022-08-29 17:08:39', 'Release Right Breast, Percutaneous Approach'),
--        (2, 3, 4, '2022-11-16 17:34:23', 'Excision of Cerebellum, Percutaneous Endoscopic Approach, Diagnostic'),
--        (3, 3, 6, '2022-07-21 12:48:50',
--         'Removal of External Fixation Device from Right Carpal, Percutaneous Endoscopic Approach'),
--        (4, 7, 8, '2022-01-19 13:58:17',
--         'Extirpation of Matter from Large Intestine, Via Natural or Artificial Opening Endoscopic'),
--        (5, 5, 10, '2022-11-10 17:04:36', 'Excision of Left Greater Saphenous Vein, Percutaneous Approach, Diagnostic');
--
-- INSERT INTO `doctor` (`id`, `specialization`, `salary`)
-- VALUES (1, 6, 2644),
--        (3, 2, 2456),
--        (5, 16, 2714),
--        (7, 19, 4876),
--        (9, 18, 1759);
--
-- INSERT INTO `specialization` (`id`, `name`)
-- VALUES (1, 'Allergy and immunology'),
--        (2, 'Anesthesiology'),
--        (3, 'Dermatology'),
--        (4, 'Diagnostic radiology'),
--        (5, 'Emergency medicine'),
--        (6, 'Family medicine'),
--        (7, 'Internal medicine'),
--        (8, 'Medical genetics'),
--        (9, 'Neurology'),
--        (10, 'Nuclear medicine'),
--        (11, 'Obstetrics and gynecology'),
--        (12, 'Ophthalmology'),
--        (13, 'Pathology'),
--        (14, 'Pediatrics'),
--        (15, 'Physical medicine and rehabilitation'),
--        (16, 'Preventive medicine'),
--        (17, 'Psychiatry'),
--        (18, 'Radiation oncology'),
--        (19, 'Surgery'),
--        (20, 'Urology');

INSERT INTO `user` (`name`, `password`, `email`) VALUES ('Jacquelin Labbe', 'gCxS9aPx3', 'jlabbe0@unesco.org');
--        (2, 'Wilma Padkin', 'c4dJWraw', 'wpadkin1@paginegialle.it'),
--        (3, 'Jannel Rustich', '8MYaB2', 'jrustich2@seesaa.net'),
--        (4, 'Liza Panner', 'wRqWygeoBY', 'lpanner3@va.gov'),
--        (5, 'Cody Ca', 'gdiLDeeAj', 'cca4@t.co'),
--        (6, 'Nedi Juppe', 'tF1n9Mt', 'njuppe5@jimdo.com'),
--        (7, 'Lyndell Arlett', 'S1QjsUD8', 'larlett6@mashable.com'),
--        (8, 'Monah Hacquard', 'VuYgp2AK', 'mhacquard7@tinypic.com'),
--        (9, 'Brandise Stranieri', 'DjHY6vh79FAM', 'bstranieri8@illinois.edu'),
--        (10, 'Lodovico Haysham', 'xZsxPWg3B', 'lhaysham9@gnu.org');
--     (11, 'Superuser', 'admin', 'admin');