version: "3.9"
services:
#  web:
#    build: .
#    ports:
#      - "5050:5000"

  db:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ecorp
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "5051:3306/tcp"
    volumes:
#      - db_data:/var/lib/mysql Caso não seja preciso a persistência dos dados entre reloads
      - ./db:/docker-entrypoint-initdb.d:ro
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - "5052:80/tcp"

volumes:
  db_data:

